name: Generate Files with kts
on:
  workflow_dispatch:
  pull_request:
    branches:
      - specify
    paths:
      - 'output/**'

jobs:
  generate_tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fwilhe2/setup-kotlin@main
      - name: Run the script
        run: kotlin ./generate_all.kts
      - name: Commit Generated Platform Deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update design tokens
          branch: specify
