name: Update Design Tokens

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  update-design-tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Specify CLI
        run: npm install -g @specifyapp/cli;
      - name: Pull design data from Specify
        run: |
          specify pull \
            -r @superbet/light \
            -C ./.specify/superbet-light.json \
            -p ${{ secrets.SPECIFY_TOKEN }};
          specify pull \
            -r @superbet/dark \
            -C ./.specify/superbet-dark.json \
            -p ${{ secrets.SPECIFY_TOKEN }};
          specify pull \
            -r @superbet/iconography-single-color \
            -C ./.specify/icons-single-color.json \
            -p ${{ secrets.SPECIFY_TOKEN }};
      - name: Run the script
        run: kotlin ./generate_all.kts
      - name: Commit Generated Platform Deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Android resources generated
          branch: specify
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update design tokens
          title: 'Update design tokens'
          body: >
            The design tokens and assets contained in this PR come from your [Specify](https://www.specifyapp.com) repositories set in your GitHub Action.<br>
            <br>
            Useful resources:<br>
            - ℹ️ [Documentation](https://specifyapp.com/developers)<br>
            - 🙋 [Help Center](https://help.specifyapp.com)<br>
            - ⚙️ [Parsers](https://github.com/Specifyapp/parsers/)<br>
            - 👥 [Join our Discord community](https://discord.com/invite/vMkDk4CbG4)<br>
            <br>
            If you need further assistance feel free to reach out at: [louis@specifyapp.com](mailto:louis@specifyapp.com).
          branch: specify
          labels: Design Tokens
